### ISSUE TITLE
Drawer Item - Headers

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#102]
[Dev Mode -Figma Link](https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=3638-13907&m=dev)

```[tasklist]
### Variants
- [ ] header + tabs
- [ ] Header + tabs + back button
```
## Design Notes

<img width="556" alt="Screenshot 2024-07-30 at 11 12 06 AM" src="https://github.com/user-attachments/assets/bfa07fcb-a94a-4a3e-b874-e8a36a2da99d">

- This Component uses [tabs with underline](https://flowbite.com/docs/components/tabs/#tabs-with-underline) component
- Ignore the other three variants for now.

**Comment by Madeline-UX** [comment]
@jeff-mccoy - Use the components for styles/structure of components but suggested not using flowbite javascript for business logic. Write the code in-line for tabs.
