### ISSUE TITLE
Status Colors

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-runtime#129]
### Is your feature request related to a problem? Please describe

As a DevOps engineer or system administrator,
I want to see color-coded status indicators for all Kubernetes resources in our application,
So that I can quickly assess the health and state of our infrastructure at a glance.

### Acceptance Criteria

The application uses a consistent color scheme for all Kubernetes resource statuses:

<img width="400" alt="Screenshot 2024-08-01 at 3 30 57 PM" src="https://github.com/user-attachments/assets/907feda2-03a8-4804-b653-4dfd01c99822">

- [ ] Green for success/healthy states
- [ ] Blue for informational/ongoing processes
- [ ] Orange for warnings and pending states
- [ ] Red for errors and critical issues
- [ ] Grey for disabled or inactive resources

1. The color scheme is applied uniformly across all resource types (Pods, Deployments, Services, etc.) as per the provided recommendations.
2. Each resource in the UI displays its status using the appropriate color.
3. Color indicators are accompanied by text labels for clarity and accessibility.

### Design Resources

[Color Status Design Guidelines](https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=3723-2949&t=htuNy6u4cok3uBiu-1)

**Comment by adam-defenseunicorns** [comment]
@jeff-mccoy is this something we can toss back into the backlog for someone else to take on?

**Comment by BillyFigueroa** [comment]
> @jeff-mccoy is this something we can toss back into the backlog for someone else to take on?

Is this ticket front end only?
