### ISSUE TITLE
Ephemeral Test Cluster

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#148]
### Is your feature request related to a problem? Please describe
The team needs an easily accessible, demo environment for testing and demonstration purposes without requiring installation or complex setup. Currently, there's no simple way for people to quickly interact with and evaluate UDS Runtime.

### Describe the solution you'd like
**Given** a need for a demo environment (cluster)
**When** a demo cluster is set up with UDS Runtime
**Then** it should:

- Be accessible to Defense Unicorns
- Be ephemeral and recreated regularly (e.g., every hour, six hours, or day)
- Have minimal security measures due to its temporary nature
- Be easily shareable via a link 
- Possibly use an AWS load balancer URL with hashes
- Have no access to perform significant actions
- Serve as a continuously available "snapshot" for immediate usability testing and idea validation

### Describe alternatives you've considered
Integrating into staging environments or UDS core was considered but deemed to require more careful security considerations. (Future iteration for longer term testing)

### Additional context
- While secrets may be exposed, it's not a major concern due to the cluster's ephemeral nature and limited access.
- The primary goal is to provide a simple, accessible way for people to interact with and test the system quickly.

**Comment by UncleGedd** [comment]
@TristanHoladay and I discussed:
1. Setup EC2 instance with a custom AMI containing all necessary tooling
2. Spin up ALB in front of EC2 for easy DNS
3. (potentially) use an old domain, like baffles, that we own
4. Set up ASGs to spin the instance up/down at night
