### ISSUE TITLE
Frontend terminal command (o + enter) does not seem to work

### ISSUE THREAD

**Issue by DannyDTenacious** [defenseunicorns/uds-runtime#171]
In the frontend terminal, o + enter does not seem to work (no browser opens); did not test the other commands.

### Visual Proof (screenshots, videos, text, etc)
<img width="229" alt="Screenshot 2024-08-07 at 2 57 42 PM" src="https://github.com/user-attachments/assets/98e0be35-8483-4abc-88f6-9f039d19a5fa">

**Comment by TristanHoladay** [comment]
@DannyDTenacious when you tried did you do `o` then `enter` or `o` then `+` then `enter`? i just tried `o` then `enter` and it opened in the browser for me.

**Comment by DannyDTenacious** [comment]
@TristanHoladay This was reported by Brandi M. from when I interviewed her for feedback. I can ask for more details when she returns to the office. Is there any other specific information I should gather?

**Comment by TristanHoladay** [comment]
@DannyDTenacious oh ok. mmm, maybe what browser she's expecting it to open / if she has a default browser set. also, i'm not sure how much we can fix this if there is something that doesn't work for certain individuals because that's a feature from vite (the frontend dev server).
