### ISSUE TITLE
Discuss replacing svelte-apexcharts dependency

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#186]
### Describe what should be investigated or refactored

The [svelte-apexcharts](https://github.com/galkatz373/svelte-apexcharts) dep hasn't been updated in 4 years. Discuss with @jeff-mccoy if we swap this for something else

**Comment by BillyFigueroa** [comment]
# Options
Looked into some options. I did not do all the research likely needed but I did try to find the best options I could find. Some of more popular and known and some are smaller but more actively maintained

## Here is the list

- [ ] https://github.com/mhkeller/layercake
- [ ] https://github.com/SauravKanchan/svelte-chartjs (based off https://www.chartjs.org/)
- [ ] https://www.layerchart.com (https://www.layerchart.com/docs/examples/Area#multiple_series_(using_overrides))
- [ ] https://github.com/apache/echarts (https://echarts.apache.org/en/index.html)

There is also this…
- [ ] https://www.sveltecharts.com/

but this seems like individual graphs which could present it’s own problem for maintenance

We can also just try to find a typescript library and add any potential reactivity that needs to be added. Something like this?
- [ ] https://github.com/apache/echarts
