### ISSUE TITLE
Update favicon and preview

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#207]
### Is your feature request related to a problem? Please describe

Fix preview + favicon

![image](https://github.com/user-attachments/assets/cb8dcd62-efa9-4331-9be9-cc73b0d59fcf)

**Comment by Madeline-UX** [comment]
I am thinking we use just doug - but wanted to ask here in case there are any reasons to not. Doug is in UDS logo so it makes sense. @jeff-mccoy

**Comment by Madeline-UX** [comment]
Here is the link for the file provided by Andrew Greene     <link rel="icon" href="%sveltekit.assets%/doug.svg" />
