### ISSUE TITLE
Fix unstyled content

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#208]
### Environment

Device and OS: iOS (mobile)

### Steps to reproduce

Fix the unstyled content when viewing on mobile

![image](https://github.com/user-attachments/assets/2057e6be-8f10-4eda-8d46-93431a72e6ad)

**Comment by BillyFigueroa** [comment]
@UncleGedd I am not seeing this as an issue on my iOS phone. Do you still see this issue?

**Comment by UncleGedd** [comment]
Yeah I could replicate by refreshing the page. There's something weird with CSS transitions on mobile

**Comment by BillyFigueroa** [comment]
> Yeah I could replicate by refreshing the page. There's something weird with CSS transitions on mobile

Ahhh now I see it when I reload page. Got it. Thanks @UncleGedd
