### ISSUE TITLE
Improve Pepr implementation efficiency and UX

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#238]
### Description
Need to investigate and implement optimizations for loading and rendering Pepr data

### Notes
- don't bind every time (use same pattern as observers)
- do Pepr streams on demand, but not forever

![Screenshot 2024-09-26 at 11 12 36 AM](https://github.com/user-attachments/assets/6ee71dad-c584-4fdc-aa8a-2e4b9197a72a)

**Comment by TristanHoladay** [comment]
not sure if this is the right approach, but was wondering about this, and if you can't use the informer factories (regular or dynamic) maybe you can use the underlying `watch` api to create your own: https://stackoverflow.com/questions/40975307/how-to-watch-events-on-a-kubernetes-service-using-its-go-client

**Comment by UncleGedd** [comment]
Closed with a slight improvement (less noticeable on large clusters), but we need to refactor the backend Pepr monitor logic. Tracking in https://github.com/defenseunicorns/uds-runtime/issues/433
