### ISSUE TITLE
Details view 401 when API token auth enabled

### ISSUE THREAD

**Issue by decleaver** [defenseunicorns/uds-runtime#274]
- fix details view when auth enabled (pass token to request)
- Redirect unauth's views to unauth page (potential fix: refactor auth code to move to layout (load) vs authpage (onmount)
- wrap eventsource to cleanup multiple checks on multiple instantiations of eventSource

**Comment by UncleGedd** [comment]
> wrap eventsource to cleanup multiple checks on multiple instantiations of eventSource

You may also want to do this with `fetch`
