### ISSUE TITLE
Design doc for API Auth

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#294]
### Describe what should be investigated or refactored

Write a design doc for API auth as it will be used when running `uds ui`

#### Considerations
- discuss why we need this feature and who the users are
- detail out the requirements to the best of our knowledge
- session storage vs cookies vs other tech
- desired behaviors (ie. what happens when the user refreshes, navigates away, closes the window, etc)

#### Design doc examples
- [Engineering coda](https://coda.io/d/Engineering_dfvozy2Mzwt/Design-Doc-Process-and-Goals_suSqFbXW?searchClick=5985fde4-9c89-4dc7-b278-3a914f0ca569_fvozy2Mzwt#_lulfdjoH)
- [UDS state](https://github.com/defenseunicorns/uds-cli/blob/main/design-docs/0001-bundle-state.md)

**Comment by decleaver** [comment]
working branch - https://github.com/defenseunicorns/uds-runtime/tree/api-auth-state-design-doc
