### ISSUE TITLE
Research Security Hub

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#304]
### Describe what should be investigated or refactored

Dig into uds-security-hub and explore how data is created and how we could ingest it via UDS Runtime
- be sure to think about how false positives might be addressed
### Links to any relevant code

https://github.com/defenseunicorns/uds-security-hub-scanning?tab=readme-ov-file#how-to-download-and-verify-uds_security_hubdb

https://defenseunicorns.miro.com/app/board/uHjVOf4_oTs=/

**Comment by UncleGedd** [comment]
Currently discussing with @koesbong and @mjnagel where the security hub DB should live

**Comment by adam-defenseunicorns** [comment]
See #367
