### ISSUE TITLE
Overview / Dashboard

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-runtime#33]
## User Story 
The dashboard will show an overview of the cluster. It meets two of our desired user experience stories:

As an SRE, I would like meaningful metrics about cluster resource utilization, including available memory, storage, and disk.

As an SRE, I would like comprehensive visibility and tracking of deployed resources, including UDS Bundles, packages

### Describe the solution you'd like

Given a user is connected to a cluster and on the Dashboard page
Then they should see the following data regarding the cluster's current state
- Memory Usage (widget)
- Storage usage (widget)
- Packages deployed to cluster (UDS Core)
- Packages deployed to cluster (not UDS core)
- Security posture (widget)
- List of any failures in cluster - link to relevant page.

## Figma Design
https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Engine-(UI%2FCLI)?node-id=3497-16205&m=dev&t=qLmpasCpSScC2QUV-1

## Wireframes 
![Screenshot 2024-07-23 at 6 50 09 PM](https://github.com/user-attachments/assets/cca1dbab-f9ec-49cd-89e0-e388044a5e56)

![IMG_7669](https://github.com/user-attachments/assets/bc69a270-024a-4b60-a0a4-fdc183de59d9)

**Comment by adam-defenseunicorns** [comment]
Finished for v0.1.0
