### ISSUE TITLE
K8s Resource Detail View

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-runtime#34]
### User Story

As a user of the platform management tool,
I want to be able to click on any element within the application
So that a right drawer appears with detailed information about the selected element

### Acceptance Criteria

- **Given** I am an SRE, using the UDS web app
- **When** I click on a resource/element in the app
- **Then** I see a view with details of that resource

A drawer slides in from the right side of the screen.
The drawer contains multiple sections with relevant information about the selected element.
Each section can display multiple lines of data.

### Additional context
The data in the drawer can include:

Text
Links (clickable and visually distinct)
Icons (relevant to the information being presented)

The drawer should have a clear way to close it (e.g., a close button or clicking outside the drawer).
The drawer should not obstruct critical parts of the main interface.
The transition of the drawer opening and closing should be smooth and animated.

How might we ensure information is both scannable and readable when dene?

## Designs
[Figma Dev Mode Link](https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=3664-12791&m=dev)

Component: Drawer
Placement = Right
Backdrop = False
body scrolling = true
edge = false

<img width="1434" alt="Screenshot 2024-07-26 at 11 19 22 PM" src="https://github.com/user-attachments/assets/882b5148-2836-4eef-b935-28a458e172a9">

<img width="712" alt="Screenshot 2024-07-26 at 11 24 19 PM" src="https://github.com/user-attachments/assets/7b03e503-475e-4d77-9512-123d69cb333a">

**Comment by Madeline-UX** [comment]
Examples from Lense
<img width="1028" alt="Screenshot 2024-07-25 at 11 46 15 AM" src="https://github.com/user-attachments/assets/43cdaf07-1eb4-4fbb-a714-3ee424bb2fe9">
