### ISSUE TITLE
UDS Runtime Deployed to Internal Staging & Prod

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#347]
### Is your feature request related to a problem? Please describe

The UDS Runtime team would like to have UDS Runtime deployed to the burning.boats (staging) and uds.is (prod) environments so that we can begin properly testing on a longer lasting cluster with more users.

If we answer [this ticket](https://github.com/defenseunicorns/uds-runtime/issues/346) will this issue resolve itself the next time UDS Core is deployed to these environments?

### Describe the solution you'd like

- **Given** UDS Runtime releases a new update
- **When** the deployment process for burning.boats & uds.is
- **Then** UDS Runtime is updated/deployed to those environments

- [ ] deployed to burning.boats
- [ ] deployed to uds.is

### Additional context

Auth integration required first to make sure that secrets or any sensitive data are not accessible. Should pose no risk to the clusters themselves since Runtime is view only for now.

**Comment by TristanHoladay** [comment]
this was done a few weeks ago https://github.com/defenseunicorns/uds-infrastructure/pull/424 . the deployment failed for what looked like memory issues. at the time other things were a priority so I didn't dig into it too much with the infra team. If we end up adding Runtime to Core then we'll need to remove the separate deployment in the infra repo.

**Comment by TristanHoladay** [comment]
remove runtime -- https://github.com/defenseunicorns/uds-infrastructure/pull/478
update Core with Runtime - https://github.com/defenseunicorns/uds-infrastructure/pull/479

**Comment by TristanHoladay** [comment]
Runtime is currently up in Staging, but we had to manually change resource limits to get it to deploy. This means it's not deployed in Prod. Waiting on the [0.5.0 release](https://github.com/defenseunicorns/uds-runtime/pull/358) and then we'll need to wait for Core to release with Runtime 0.5.0.

Then we can PR the infra repo with a bundle override to set those resource limits.

**Comment by TristanHoladay** [comment]
adds latest release of Core with latest Runtime and overrides resource limits (current fix) for getting Runtime into staging and Prod https://github.com/defenseunicorns/uds-infrastructure/pull/497

**Comment by TristanHoladay** [comment]
confirmed with uds-infra team that Runtime is successfully running in staging and prod. Currently behind admin gateway so not easily viewed.
