### ISSUE TITLE
Enable Switching between Clusters

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#348]
### Is your feature request related to a problem? Please describe

As an SRE, I find it frustrating and time-consuming to constantly switch between different interfaces when I need to manage multiple Kubernetes clusters. Currently, Runtime doesn't provide a way to easily switch between clusters. 

### Describe the solution you'd like

- **Given** the SRE is logged into Runtime and viewing information for a specific Kubernetes cluster
- **When** they select a different cluster from a dropdown menu or similar UI element
- **Then** Runtime should
  - Switch the context to the selected cluster
  - Update all relevant information and metrics to reflect the newly selected cluster
  - Maintain any applied filters or views that are cluster-agnostic
  - **Provide a clear visual indication of which cluster is currently active**

### Describe alternatives you've considered

- Creating separate dashboard instances for each cluster: This would be less efficient and could lead to increased resource usage.
- Using browser tabs to manage different clusters: This approach lacks integration and doesn't provide a seamless experience. Users may decide to do this anyway and may be worth exploring how it is being used in prod.

### Additional context

- The feature should support switching between all clusters that the user has permission to access.
- Consider adding a "favorites" or "recent clusters" list for quick access to frequently used clusters. (validation needed, not in scope)
- Ensure that the cluster switching process is fast and doesn't disrupt the user's workflow.

**Comment by adam-defenseunicorns** [comment]
@DannyDTenacious I removed you as being assigned and the "Design Needed" label because I think it is complete from the design perspective.

**Comment by Madeline-UX** [comment]
UX flow (simplified)

Selecting cluster
> When a user is on any screen and clicks the cluster dropdown from the global nav
> then a select modal with all of the clusters from their local/primary kubeconfig will show

Changing Cluster
> when a user selects a new cluster form the dropdown
> then the content on the screen clears completely
> then the user sees the loading screen (2 - 3 seconds min) with the name of the cluster that is being loaded)
> When the cluster is ready the dashboard of the newly selected cluster is shown.
