### ISSUE TITLE
Show All Pepr Data

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-runtime#35]
### Is your feature request related to a problem? Please describe
The `Monitor > Pepr` table is showing only a subset of the data. 

### Describe the solution you'd like

- **Given** a user
- **When** navigating to the pepr table
- **Then** sees the details of these pepr actions (e.g. mutated and denied)

![Screenshot from 2024-07-23 12-30-01](https://github.com/user-attachments/assets/e00a58cf-f9d7-4f29-865f-1e529e42ba7c)

## Designs 

Figma File https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Engine-(UI%2FCLI)?node-id=3583-20345&m=dev

**Comment by Madeline-UX** [comment]
Design options

## Option 1 
Policy name/message included in a cell then an optional button to show more details for those with longer messages
 
Screenshot 2024-07-23 at 5.41.22 PM.png


Screenshot 2024-07-23 at 5.41.31 PM.png


Screenshot 2024-07-23 at 5.45.48 PM.png
