### ISSUE TITLE
Pod counts do not line up between views

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-runtime#361]
### Environment

Device and OS: MBP, macOS + Colima
App version: 0.4.0
Kubernetes distro being used: k3d
Other: Deployed with UDS Core

### Steps to reproduce

1. Deploy uds-core, latest release (0.27.3), with the demo bundle for easy deployment (`uds deploy k3d-core-demo:0.27.3`)
1. View the main landing page (https://runtime.admin.uds.dev/) and pod count. In my case this is 49.
2. Click into the pod view (https://runtime.admin.uds.dev/workloads/pods) and view the count at the top. In my case this is 41.

### Expected result

Pod counts are aligned between views.

### Actual Result

Pod counts differ between views.

### Visual Proof (screenshots, videos, text, etc)

![image](https://github.com/user-attachments/assets/4d0ae17c-932d-4106-9da0-d332190afaab)

### Severity/Priority

Low/Medium - data "sum" consistency issue but does not appear to actually affect individual data points shown.

**Comment by adam-defenseunicorns** [comment]
@BillyFigueroa it also looks like the CPU and memory usage status bars are not rendering correctly.

**Comment by mjnagel** [comment]
Comparing data with k9s it appears that the sum on the pods page is correct, while the landing page is incorrect (in the example above 41 lined up with the sum that k9s listed).
