### ISSUE TITLE
Use TLS when running in desktop mode

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#365]
### Is your feature request related to a problem? Please describe

Today we are using `localhost` which limits us to HTTP/1 which in turn limits our number of SSE connections to 6. By upgrading to TLS (ie. use `runtime-local.uds.dev`) we can overcome this SSE connection limit.

### Additional context

When SSE connections are limited, it means users can't have Runtime open in more 1 tab/window at a time

**Comment by TristanHoladay** [comment]
closing in favor of #378
