### ISSUE TITLE
pepr monitor view not closing properly

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#37]
Jeff found that pepr is not closing properly creating multiple endpoints. 

As you migrate from one view to another from pepr monitor the old pepr is not removed creating multiple.

**Comment by TristanHoladay** [comment]
![Screenshot from 2024-07-24 10-38-44](https://github.com/user-attachments/assets/8c8eb6e2-dd73-4439-8abc-355dc9316c56)
