### ISSUE TITLE
Graceful handling of unavailable K8s CRDs

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#376]
### Is your feature request related to a problem? Please describe

When deploying applications that depend on Custom Resource Definitions (CRDs), the absence of these CRDs can lead to deployment failures and errors. Currently, the system does not gracefully handle situations where required CRDs are missing.

### Describe the solution you'd like

- **Given** a cluster where certain CRDs are not available
- **When** an application that depends on these CRDs is deployed
- **Then** Runtime should...
  - Detect the missing CRDs
  - Log warnings about the unavailable CRDs
  - Offer clear error messages and documentation on how to resolve CRD-related issues
  - **_Other/More??_**

### Describe alternatives you've considered

1. Pre-deployment CRD check: Implement a pre-deployment step that verifies all required CRDs are present before initiating the deployment process. Do we already do any of this in CLI and if not would this be worth looking into?
2. Automatic CRD installation: Automatically install missing CRDs as part of the deployment process. This could potentially solve the issue but might not be desirable in all environments due to security or governance concerns.

### Additional context

This feature would be particularly useful for organizations managing multiple Kubernetes clusters with varying CRD availability, such as development, staging, and production environments. It would also benefit teams working on applications that use optional features dependent on specific CRDs, allowing for more flexible deployments based on the target environment's capabilities.

**Comment by decleaver** [comment]
Currently if there is a missing CRD you get logs similar to the following:
`E0930 08:40:17.371313   40214 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch uds.dev/v1alpha1, Resource=exemptions: failed to list uds.dev/v1alpha1, Resource=exemptions: the server could not find the requested resource" logger="UnhandledError"`
and  the table displays "No resources found". Not sure what is desired.
![image](https://github.com/user-attachments/assets/beaa4ce0-72d0-403c-b1d9-cfd7188d6d8c)
