### ISSUE TITLE
Network files loading slow

### ISSUE THREAD

**Issue by BillyFigueroa** [defenseunicorns/uds-runtime#39]
We have an issue with certain files taking 45+ seconds to load locally

**Comment by BillyFigueroa** [comment]
I have reviewed this issue locally and I cannot replicate the bahvrior @jeff-mccoy was seeing on his machine. @TristanHoladay also did some tests locally and was not able to re-produce this either

**Comment by jeff-mccoy** [comment]
yeah I _think_ it was a funky cache in .sveltekit with an older version, blew everything away and it's been fine since, closing and can re-open if it happens again.
