### ISSUE TITLE
SecurityHub: Confirm Cluster Overview data mapping

### ISSUE THREAD

**Issue by decleaver** [defenseunicorns/uds-runtime#391]
Verify and confirm mappings for all data being returned to values in security hub db

**Comment by koesbong** [comment]
@decleaver did you already get what you need or should we keep this open still?

**Comment by TristanHoladay** [comment]
met as a team with @DannyDTenacious and confirmed view fields and what data is needed for each field. @UncleGedd created a coda doc for the Security Hub team to know exactly what we need.
