### ISSUE TITLE
desktop mode - persist login between windows

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#392]
### Steps to reproduce

1. Run `uds ui`
2. Open another browser window and navigate to localhost:8080

### Expected result

I should still be logged in

### Actual Result

I see the "Could not authenicate" page

### Visual Proof (screenshots, videos, text, etc)

![Screenshot 2024-09-25 at 1 23 08 PM](https://github.com/user-attachments/assets/2dc8c738-1172-47ed-b87f-c9993f9c8c2e)

**Comment by BillyFigueroa** [comment]
@UncleGedd wasn't this issue addressed in you are a PR from @decleaver ?

**Comment by UncleGedd** [comment]
Yes, closing this issue with https://github.com/defenseunicorns/uds-runtime/pull/405
