### ISSUE TITLE
Overview Dashboard: Events Logs Widget

### ISSUE THREAD

**Issue by DannyDTenacious** [defenseunicorns/uds-runtime#409]
### Is your feature request related to a problem? Please describe

As a consumer of UDS Runtime, I would like to see an Events Logs Widget with the same information as populated in the Monitor/Events page. Please add messaging "Events are displayed for 1 hour, after which they are expunged." to the information tooltip. (Open language suggestions)

### Describe the solution you'd like
Information table as show in Figma (link below)
Zero State: When there are no events to display, surface the message "No events have occurred within the last hour."

### Additional context
https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=4325-5166&m=dev
<img width="824" alt="Screenshot 2024-10-02 at 2 37 20 PM" src="https://github.com/user-attachments/assets/57bc1a46-ed48-4925-be37-e225f8eb00e0">

Future state (do not show): 
Drop down filter
Search bar

**Comment by BillyFigueroa** [comment]
@DannyDTenacious the monitor/events table does not have a status field. Is this widget supposed to be for `monitor/pepr` events? the data being populated here doesn't seem to be inline with what we see in the monitor events or pepr pages. Here is the events table

<img width="1329" alt="Screenshot 2024-10-03 at 12 23 22 PM" src="https://github.com/user-attachments/assets/b8b11596-9aca-4a0e-a946-718dc3219720">
