### ISSUE TITLE
Overview Dashboard: Packages Widget

### ISSUE THREAD

**Issue by DannyDTenacious** [defenseunicorns/uds-runtime#410]
As a consumer of UDS Runtime, I would like to see an overview of what applications are available within the cluster via a Packages Widget on the Overview Dashboard. 

### Describe alternatives you've considered
If it's not possible for a user to click on the "Open App" button and go directly to the application, please replace button with status information. 

### Additional context
https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=4325-5166&m=dev
<img width="414" alt="Screenshot 2024-10-02 at 2 41 09 PM" src="https://github.com/user-attachments/assets/91a30f4e-ec5d-4f6f-a911-829ba3889099">

**Comment by decleaver** [comment]
questions posted: https://defense-unicorns.slack.com/archives/C06LPB2CBT4/p1729780821191989
