### ISSUE TITLE
Overview Dashboard: Core Services

### ISSUE THREAD

**Issue by DannyDTenacious** [defenseunicorns/uds-runtime#411]
### Describe the solution you'd like

As a consumer of UDS Runtime, I would like to view a summary of core services, status and a corresponding link to view the service (as shown on the Figma design)

### Additional context
https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=4325-5166&m=dev 
<img width="412" alt="Screenshot 2024-10-02 at 2 57 35 PM" src="https://github.com/user-attachments/assets/bc294994-4eb9-4440-9822-2adea8ae7f94">

**Comment by BillyFigueroa** [comment]
This is what the Services view in OpenLens looks like

<img width="1592" alt="Screenshot 2024-10-08 at 1 14 28 PM" src="https://github.com/user-attachments/assets/cb8057ce-c47a-44ce-b199-6681ccd3ea35">

**Comment by DannyDTenacious** [comment]
Per discussion w/Madeline & Gedd in Slack: "we use the names of the functional layers (core services in out github repo); also let's remove the "View Service" link."

**Comment by BillyFigueroa** [comment]
> Per discussion w/Madeline & Gedd in Slack: "we use the names of the functional layers; also let's remove the "View Service" link."
> 
> Reasoning: Apps within functional layers can and will change. we may not always use keycloak for IDAM but does Ashton really need to be burdened by that information?

The links were removed. Can we remove them from the design?

**Comment by DannyDTenacious** [comment]
Madeline has added a note stating the links are for future; eventually this will link to a package definition page with all YAMLs. Does that work?

**Comment by BillyFigueroa** [comment]
> Madeline has added a note stating the links are for future; eventually this will link to a package definition page with all YAMLs. Does that work?

Yes
