### ISSUE TITLE
Refactor `uds ui`

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#417]
### Is your feature request related to a problem? Please describe

Don't embed `uds-runtime` into UDS CLI as this will be an issue for certain security scanners

### Describe the solution you'd like

Something like:
- Publish the Runtime frontend as a build / release artifact
- Vendor Runtime in CLI like we do with Zarf + Maru
- Embed the published frontend artifact(s) in CLI (don't forget to ensure the version matches the vendored Runtime version!)
- ???
- Profit

**Comment by UncleGedd** [comment]
cc @catsby

**Comment by TristanHoladay** [comment]
https://github.com/defenseunicorns/uds-cli/pull/967

**Comment by TristanHoladay** [comment]
there are a lot of dependency issues that happen when trying to vendor runtime. It seems that the culprit is upgrade uds-cli zarf version to `0.41.0`. Hoping that this PR https://github.com/defenseunicorns/uds-cli/pull/972 will clear up those issues and we can proceed with the vendored runtime PR.

**Comment by TristanHoladay** [comment]
completed in release [v0.18.0 of uds-cli ](https://github.com/defenseunicorns/uds-cli/releases/tag/v0.18.0)
