### ISSUE TITLE
Investigate Passing `ctx` to API test Go Functions

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-runtime#508]
It could be that we don't actually need to do this, or if we do then we might want to figure out using the context in the go func().

https://github.com/defenseunicorns/uds-runtime/blob/3034fc944bcd0a97a73f101972affe91c9ec68e9/src/test/e2e/api_test.go#L84

**Comment by TristanHoladay** [comment]
notes from pairing with @catsby:

1. for SSE streams we need the `go func()()` so keep that, but we don't need to pass `ctx` to the func.
1. we can get rid of the context entirely if we want and use a `time.Sleep()`
1. for non-SSE calls we don't need the `go func()()`

**Comment by catsby** [comment]
I opened https://github.com/defenseunicorns/uds-runtime/pull/513 for this
