### ISSUE TITLE
Use KFC 🐔 

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-runtime#87]
### Describe what should be investigated or refactored

In our e2e tests, instead of using `client-node` use KFC to interact with K8s

### Links to any relevant code

https://github.com/defenseunicorns/uds-runtime/blob/main/ui/tests/sse.spec.ts

**Comment by decleaver** [comment]
https://github.com/defenseunicorns/kubernetes-fluent-client

**Comment by TristanHoladay** [comment]
using KFC for testing, but agreed that since types from KFC are wrappers on kubernetes-client-node types then we'll stick with KCN for our types for now.
